"""add_ndvi_url_to_fields

Revision ID: 135a9639e496
Revises: 65226bf95f0a
Create Date: 2026-04-10 22:44:10.822886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "135a9639e496"
down_revision: Union[str, None] = "65226bf95f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fields", sa.Column("ndvi_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fields", "ndvi_url")
    # ### end Alembic commands ###
