"""added_expiration_time

Revision ID: 65226bf95f0a
Revises: 2a212750ad7b
Create Date: 2025-04-03 17:21:01.549425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65226bf95f0a"
down_revision: Union[str, None] = "2a212750ad7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fields",
        sa.Column(
            "expiration_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fields", "expiration_time")
    # ### end Alembic commands ###
