"""add_sar_change_url_to_fields

Revision ID: be058be0b8da
Revises: 135a9639e496
Create Date: 2026-04-10 23:22:23.556115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be058be0b8da"
down_revision: Union[str, None] = "135a9639e496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fields", sa.Column("sar_change_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fields", "sar_change_url")
    # ### end Alembic commands ###
